In [1]:
import torch

/home/huber/projects/ml-studies/misc/env/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [5]:
# Sum the content of an 1d vector
t = torch.arange(10)
torch.einsum("i->", t)

tensor(45)

In [6]:
# Sum the content of an 2d vector
t = torch.arange(10).view(2, 5)
torch.einsum("ij->", t)

tensor(45)

In [9]:
# Sum the rows of a 2d vector
t = torch.arange(10).view(2, 5)
torch.einsum("ij->i", t)

tensor([10, 35])

In [10]:
# Sum the cols of a 2d vector
t = torch.arange(10).view(2, 5)
torch.einsum("ij->j", t)

tensor([ 5,  7,  9, 11, 13])

In [12]:
# Multiply multiplication between vector and matrix
a = torch.arange(3)
b = torch.arange(12).view(3, 4)
torch.einsum("i,ij->j", a, b)

tensor([20, 23, 26, 29])

In [23]:
# Element-wise multiplication between vector and matrix and them sum along the rows
classic_way = (a.unsqueeze(-1) * b).sum(dim=-1)
einstein_way = torch.einsum("i,ij->i", a, b)
print(classic_way, einstein_way)

tensor([ 0, 22, 76]) tensor([ 0, 22, 76])


In [28]:
# Element-wise multiplication between vector and matrix
torch.einsum("i,ij->ij", a, b)

tensor([[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [16, 18, 20, 22]])

In [34]:
# Dot product between two vectors
a = torch.arange(10)
b = torch.arange(5, 15)
torch.einsum("i,i->", a, b)

tensor(510)

In [36]:
# Trace - sum over the main diagonal
c = torch.arange(25).view(5, 5)
d = torch.arange(10, 20).view(5, 2)
torch.einsum("ii", c)

tensor(60)

In [37]:
# Element-wise multiplication + transpose
torch.einsum("ij,ij->ji", c, c)

tensor([[  0,  25, 100, 225, 400],
        [  1,  36, 121, 256, 441],
        [  4,  49, 144, 289, 484],
        [  9,  64, 169, 324, 529],
        [ 16,  81, 196, 361, 576]])